### ISSUE TITLE
TosakaUCW's blog

### ISSUE THREAD

**Issue by TosakaUCW** [TosakaUCW/TosakaUCW.github.io#18]
https://tosakaucw.org/friend/

**Comment by removeif** [comment]
友链数据中，"valid": 0 代表异常网站，"valid": 1 或者不填代表正常网站。可以自己配置，"stopTime": "2019.09.09"代表异常时访问的时间
{
"date": "2019.09.09",
"stopTime": "2019.09.09",
"src": "https://cdn.jsdelivr.net/gh/removeif/removeif.github.io/images/tuzi.jpg",
"name": "@辣椒の酱",
"desc": "后端开发，技术分享。",
"url": "https://removeif.github.io/",
"valid": 0
}

**Comment by TosakaUCW** [comment]
> @removeif
> 友链数据中，"valid": 0 代表异常网站，"valid": 1 或者不填代表正常网站。可以自己配置，"stopTime": "2019.09.09"代表异常时访问的时间
> {
> "date": "2019.09.09",
> "stopTime": "2019.09.09",
> "src": "https://cdn.jsdelivr.net/gh/removeif/removeif.github.io/images/tuzi.jpg",
> "name": "@辣椒の酱",
> "desc": "后端开发，技术分享。",
> "url": "https://removeif.github.io/",
> "valid": 0
> }

tosakaucw.github.io，我是同时deploy到这个vps和github的，但很多时候vps这边要过很久才会有变化，尝试过清理浏览器缓存后重新访问，但没什么效果
